language: objective-c

osx_image: xcode8.1

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - gem install fastlane -NV

cache:
  yarn: true

install:
  - yarn
  - gem update fastlane

script:
  - fastlane test