matrix:
  include:
    - language: android
      os: linux
      sudo: required
      node_js: false
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      before_install:
        - nvm install 7
        - node --version
        - travis_retry curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - travis_retry sudo apt-get update -qq
        - travis_retry sudo apt-get install -y -qq yarn
        - travis_retry gem install fastlane
      install:
        - yarn
      android:
        components:
          - build-tools-23.0.1
          - android-23
      script:
        - fastlane test

    - language: objective-c
      os: osx
      osx_image: xcode8.2
      node_js: false
      before_install:
        - nvm install 7
        - node --version
        - travis_retry npm install -g yarn
        - yarn -version
        - gem update fastlane
      install:
        - travis_retry gem install xcpretty
        - travis_retry yarn
      script:
        - fastlane test_ios