language: node_js
node_js:
  - "6.9"
  - "7.1"
sudo: false
cache:
  directories:
    - $HOME/.yarn-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
env:
  - NODE_ENV='test'

matrix:
  include:
    - language: android
      os: linux
      sudo: required
      node_js: false
      before_install:
        - nvm install 7
        - node --version
        - travis_retry curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - travis_retry sudo apt-get update -qq
        - travis_retry sudo apt-get install -y -qq yarn
      install:
        - yarn
      android:
        components:
          - build-tools-23.0.1
          - android-23

      script:
        - fastlane test_ios

    - language: objective-c
      os: osx
      osx_image: xcode8.2
      node_js: false
      before_install:
      - nvm install 7
      - node --version
      - travis_retry npm install -g yarn
      - yarn -version
      - gem update fastlane

      install:
        - travis_retry gem install xcpretty
        - travis_retry yarn

      script:
        - fastlane test_ios